### ISSUE TITLE
While installing using the web installer, the 'install' button is disabled. 

### ISSUE THREAD

**Issue by isha-arunnegi** [Blazam-App/BlazamSetup#3] opened 2024-01-30 08:54 UTC
Hi Admin

I am trying to install Blazam using web installer. I am using MySQL and under IIS on windows10 pro. The connection to MySQL was successful but in the final stage the "Install" button is inactive. 
What could be wrong?
snapshots attached.

Thanks

[
![blazam_installation_issue](https://github.com/Blazam-App/BLAZAM/assets/150012363/81f2ff70-92b9-42b7-b26b-6879e55471a0)
](url)

![image](https://github.com/Blazam-App/BLAZAM/assets/150012363/dffafd5e-8e4d-400c-9d75-4f52bda88946)

**Comment by jacobsen9026** [comment] 2024-01-31 00:42
Hello @isha-arunnegi ,

There should be no reason not to be able to click Install on the "Confirm" step. 

I've added a force enable when loading the "Confirm" step for the "Install" button.
I've also changed the way the Database check enables the "Next" button, but that one makes way less sense, it should truly not be possible to pass the test and not enable the "Next" button.


These changes along with a handful of other bugfixes for the installer have been released at https://github.com/Blazam-App/BlazamSetup/releases/tag/Beta-RC1

Thank you for helping make Blazam better.

**Comment by isha-arunnegi** [comment] 2024-02-01 05:31
Thanks a lot Chrus for the lightning fast fix!
My installation went through fine.

But the website is not up. When I open the website I see this error:

[image: image.png]

I suspect the web.config file path is highlighted.
Can you please give your inputs on this?

Thanks
Arun

**Comment by jacobsen9026** [comment] 2024-02-08 21:44
Hi Arun,

The image is not displaying for me. Could you please try re-posting?

**Couple of verification questions**
1. Did you install to IIS or as a service?
2. What DB type did you choose?

**If the page shows 503 or other web server error page follow this section**
If the app is completely failing to load, we may need to look at the Application Event Log to determine the cause

After attempting to load the website on a browser, check the Application Event Log immediately following an error page. Check the most recent errors to see if they are referring to Blazam.

Lastly, reply back here with what you've found.

**If the page shows "Oops" or "Something terrible has happened" follow below**
The web installer should have configured the file appsettings.json in the installed directory.

I would not suggest you post the entire contents of the file as it contains private information.

To troubleshoot, please check the following:

1. appsettings.json exists in the chosen install directory
3. appsettings.json contains a "DBConnectionString" within the "ConnectionStrings"  { }'s like ` "ConnectionStrings": {
   "DBConnectionString": "Data Source=C:\\ProgramData\\Blazam\\database.db;"
 }`
4. If you chose SQLite, verify there is a DataSource value in the "DBConnectionString"
5. If you chose SQL or MySql, verify the "DBConnectionString" starts with "Server=", that the server name/IP is corrrect along with the database, user/userID and password are correct

Again, thank you for providing valuable feedback.

**Comment by isha-arunnegi** [comment] 2024-02-09 11:03
Hi Chris

Thanks for your reply.
I have attached the image of the error.
Here is the description of error:
HTTP Error 500.19 - Internal Server ErrorThe requested page cannot be
accessed because the related configuration data for the page is invalid.

Detailed Error Information:
Module    IIS Web Core
Notification    Unknown
Handler    Not yet determined
Error Code    0x8007007b
Config Error    Cannot read configuration file
Config File    \\?\C:\inetpub\\Blazam\web.config
Requested URL    http://localhost:80/
Physical Path
Logon Method    Not yet determined
Logon User    Not yet determined
Config Source:

   -1:     0:


Thanks and Regards
Arun

**Comment by isha-arunnegi** [comment] 2024-02-09 11:08
Hi Chris

Additional info:
*Here are the contents of my "web.config" file:*
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*"
modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\BLAZAM.dll"
stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout"
hostingModel="inprocess" />
    </system.webServer>
  </location>
</configuration>



Thanks and Regards
Arun

**Comment by jacobsen9026** [comment] 2024-04-21 18:54
I'm so sorry, I lost track of this issue. I've identified the issue as the installer passing the installation path to IIS with double slashes in a part of the path.

You will have to uninstall and re-install with the latest published web installer at https://blazam.org/download or https://github.com/Blazam-App/BlazamSetup/releases/tag/Stabl-v1.1 to correct.

**Comment by isha-arunnegi** [comment] 2024-04-22 10:40
Hi Chris

Thanks for coming back on this.
I request you for a few days of time, as we have shifted on Blazam as a
service(instead of using IIS).
But we shall be exploring the IIS option as well.

Thanks

**Comment by jacobsen9026** [comment] 2024-06-07 19:41
You have no obligation to test this on IIS, but I am wondering if you have had a chance to try?

If not then I believe we can close this issue.

**Closed as completed** 2024-09-18 01:29 UTC
Labels: bug
